language: python
python:
    - "2.7"
install:
    - pip install django==1.11
    - pip install requests
    - python manage.py migrate
script:
    - python manage.py runserver
jobs:
    - include:
        - stage: "Tests"
          name: "Unit Tests"
          script: ./test 1
          name: "Integration Tests"
          script: ./test 2
        - stage: deploy
          name: "Deploy to GCP"
          script: ./deploy
