language: python
python:
    - "2.7"
install:
        - pip install --user -r requirements.txt
    - python manage.py migrate
script:
    - python manage.py check --deploy --fail-level WARNING
jobs:
    - include:
        - stage: "Tests"
          name: "Unit Tests"
          script: ./test 1
          name: "Integration Tests"
          script: ./test 2
        - stage: deploy
          name: "Deploy to GCP"
          script: ./deploy
